### ISSUE TITLE
Artalk Error Failed to load comments TypeError: Failed to fetch  Retry

### ISSUE THREAD

**Issue by zhao2022-Ux** [ArtalkJS/Artalk#1016] opened 2024-11-03 11:46 UTC
Artalk Error
Failed to load comments
TypeError: Failed to fetch

Retry

**Comment by qwqcode** [comment] 2024-11-06 10:06
检查一下可信域名是否配置正确

https://artalk.js.org/zh/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains

duplicate of #977

**Closed by qwqcode** 2024-11-06 10:06 UTC

**Comment by zhao2022-Ux** [comment] 2024-11-23 08:07
> 检查一下可信域名是否配置正确
> 
> https://artalk.js.org/zh/guide/backend/config.html#%E5%8F%AF%E4%BF%A1%E5%9F%9F%E5%90%8D-trusted-domains
> 
> Duplicate of #977

谢谢
